### PR TITLE
Only highlight selected cards from browser

### PR DESCRIPTION
**Pull request by gajewsk2**
Threw this together quickly for my personal use and thought I'd share.

### CODE REVIEW

**Comment by gajewsk2** [comment]
Anything I need to do to get this merged in? I can fork and host my own plugin if this doesn't line up with your vision for the addon. Just let me know :) Thanks for the work on addon btw, it's really quite robust.

**Comment by HelenFoster** [comment]
Hi, sorry I didn't get around to replying yet. It seems like a good idea. I've been away from these things for a while so trying to remember what I was doing...

**Comment by gajewsk2** [comment]
Any update on if this can be merged and released?

**Comment by HelenFoster** [comment]
Sorry for the further delay. It should be soon!

**Comment by HelenFoster** [comment]
I'm starting to test it.

**Comment by HelenFoster** [comment]
Currently it crashes if fed cards that don't have the right fields. I think the simplest solution might be to take the intersection of the two groups of nids (at the `if not nids` change). Does that match up with your use case?

**Comment by HelenFoster** [comment]
Thanks for your patch. I extended it somewhat before merging.

**Comment by gajewsk2** [comment]
Oh great, I'll give it a try when I get a chance. Thanks for accepting the changes.

**Pull request merged**
